version: '3.7'

services:

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - 80:80
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
    command: /bin/sh -c "envsubst '$${HUBS_HOSTNAME}' < /tmp/app.conf > /etc/nginx/conf.d/app.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./env/.htpasswd:/etc/nginx/htpasswd
      - ./webserver/app.conf:/tmp/app.conf:ro

  cassandradb:
    image: gbiffrance/ala-cassandra:1.0
    container_name: cassandradb
    volumes:
      - db_data_cassandra:/var/lib/cassandra
    entrypoint: /bin/bash -c "cp /tmp/cassandra.yaml /etc/cassandra/cassandra.yaml && cp /tmp/cassandra-env.sh /etc/cassandra/cassandra-env.sh && /entrypoint-wrap.sh"

  solr:
    image: gbiffrance/ala-solr:1.0
    container_name: solr
    environment:
      SOLR_HEAP: 4g
    volumes:
      - data_solr:/opt/solr
    ports:
      - 8983:8983

  collectory:
    image: gbiffrance/ala-collectory:1.0
    container_name: collectory
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1056
    ports:
      - 1056:1056
    env_file: ./env/.envcollectory
    volumes:
      - data_collectory:/data/ala-collectory
      - ./config/ala-collectory-config.properties:/tmp/ala-collectory-config.properties:ro
    command: /bin/ash -c "envsubst < /tmp/ala-collectory-config.properties > /data/ala-collectory/config/ala-collectory-config.properties && catalina.sh run"
    extra_hosts:
      - "hubs.gbif.fr:172.17.0.1"

  mysqldb:
    image: mysql:5.7
    env_file: ./env/.envcollectory
    container_name: mysqldb
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:ro
      - db_data_collectory:/var/lib/mysql

  biocacheservice:
    image: gbiffrance/ala-biocacheservice:1.0
    container_name: biocacheservice
    depends_on:
      - cassandradb
      - solr
    links:
      - cassandradb
      - solr
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    volumes:
      - data_nameindex:/data/lucene/namematching
      - ./config/biocache-config.properties:/data/biocache/config/biocache-config.properties:ro
      - ./config/logger-client.properties:/data/logger-client/config/logger-client.properties:ro
    extra_hosts:
      - "hubs.gbif.fr:172.17.0.1"

  biocachehubfrance:
    image: gbiffrance/ala-biocachehub:1.0
    container_name: biocachehubfrance
    depends_on:
      - biocacheservice
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/france-hub-config.properties:/data/ala-hub/config/ala-hub-config.properties:ro
      - ./config/france-hub-server.xml:/usr/local/tomcat/conf/server.xml:ro
    extra_hosts:
      - "hubs.gbif.fr:172.17.0.1"

  biocachehubtogo:
    image: gbiffrance/ala-biocachehub:1.0
    container_name: biocachehubtogo
    depends_on:
      - biocacheservice
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/togo-hub-config.properties:/data/ala-hub/config/ala-hub-config.properties:ro
      - ./config/togo-hub-server.xml:/usr/local/tomcat/conf/server.xml:ro
    extra_hosts:
      - "hubs.gbif.fr:172.17.0.1"

  biocachehubbenin:
    image: gbiffrance/ala-biocachehub:1.0
    container_name: biocachehubbenin
    depends_on:
      - biocacheservice
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/benin-hub-config.properties:/data/ala-hub/config/ala-hub-config.properties:ro
      - ./config/benin-hub-server.xml:/usr/local/tomcat/conf/server.xml:ro
    extra_hosts:
      - "hubs.gbif.fr:172.17.0.1"

  nameindex:
    image: gbiffrance/ala-dyntaxaindex:1.0
    command: /bin/ash
    container_name: nameindex
    volumes:
      - data_nameindex:/data/lucene/namematching

  biocachebackend:
    image: test/ala-biocachebackend:1.1
    container_name: biocachebackend
    links:
      - biocachehubfrance
      - biocachehubtogo
      - biocacheservice
      - collectory
      - cassandradb
      - solr
    command: tail -f /dev/null
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - CASSANDRA_HOSTNAME=cassandradb
      - SOLR_HOSTNAME=solr
      - BIOCACHE_MEMORY_OPTS=-Xmx1g -Xms1g -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1055
    ports:
      - 1055:1055
    volumes:
      - data_nameindex:/data/lucene/namematching
      - data_biocachebackend:/data
      - ./config/blacklistMediaUrls.txt:/data/biocache/config/blacklistMediaUrls.txt
      - ./config/biocache-config.properties:/data/biocache/config/biocache-config.properties:ro
    extra_hosts:
      - "hubs.gbif.fr:172.17.0.1"

  static:
    image: nginx:alpine
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
    volumes:
      - ./static:/usr/share/nginx/html
    container_name: static

  bieindex:
    image: gbiffrance/ala-bieindex:1.0
    container_name: bieindex
    environment:
      - HUBS_HOSTNAME=hubs.gbif.fr
      - SOLR_HOSTNAME=solr
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./config/bie-index-config.properties:/data/bie-index/config/bie-index-config.properties
      - data_bieindex:/data
    links:
      - solr

volumes:
  db_data_cassandra:
  data_solr:
  data_collectory:
  db_data_collectory:
  data_nameindex:
  data_biocachebackend:
  data_bieindex:

