version: '3.7'

services:

  solr:
    image: gbiffrance/ala-solr:1.0
    container_name: solr
    environment:
      SOLR_HEAP: 20g
    volumes:
      - data_solr:/opt/solr
    ports:
      - 8983:8983

volumes:
  data_solr:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/data_solr
