version: '3.7'

services:

  cassandradb:
    image: gbiffrance/ala-cassandra:1.0
    container_name: cassandradb
    ports:
      - 9042:9042
    volumes:
      - data_cassandra:/var/lib/cassandra/data
      - commitlog_cassandra:/var/lib/cassandra/commitlog
    environment:
      - JVM_OPTS=-Xms15G -Xmx15G
    entrypoint: /bin/bash -c "cp /tmp/cassandra.yaml /etc/cassandra/cassandra.yaml && cp /tmp/cassandra-env.sh /etc/cassandra/cassandra-env.sh && /entrypoint-wrap.sh"

volumes:
  data_cassandra:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/data_cassandra
  commitlog_cassandra:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data_commitlog
